version: "3.1"

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    volumes:
      - ./backend:/code
    command: python /code/manage.py rundebugserver 0.0.0.0:80
    ports:
      - "8000:80"
      - "9000:9000"
    links:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://postgres@db:5432/postgres"

  redis:
    image: redis

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.210.0/24
